#!/usr/bin/env python3
"""
generate_mirofish_env.py
────────────────────────
Reads your regolo.ai credentials from .env and generates the .env file
that MiroFish expects, ready to drop into the root of the MiroFish repo.

Run:
    python generate_mirofish_env.py

Output:
    mirofish.env   (in the current directory)

Then:
    cp mirofish.env /path/to/MiroFish/.env
"""

import os
import sys
from pathlib import Path

try:
    from dotenv import load_dotenv
    load_dotenv(Path(__file__).parent / ".env")
except ImportError:
    pass


MIROFISH_ENV_TEMPLATE = """\
# ── MiroFish .env ──────────────────────────────────────────────────────────
# Generated by generate_mirofish_env.py
# Full integration guide: URL_BLOG_POST

# LLM API — regolo.ai OpenAI-compatible endpoint
LLM_API_KEY={api_key}
LLM_BASE_URL={base_url}
LLM_MODEL_NAME={model}

# Mem0 — open-source agent memory layer (no external account needed)
# https://github.com/mem0ai/mem0
MEM0_LLM_MODEL={mem0_llm}
MEM0_EMBEDDER_MODEL={mem0_embedder}
"""


def main() -> None:
    api_key      = os.environ.get("REGOLO_API_KEY", "")
    base_url     = os.environ.get("REGOLO_BASE_URL", "https://api.regolo.ai/v1")
    model        = os.environ.get("LLM_MODEL_NAME", "Llama-3.3-70B-Instruct")
    mem0_llm     = os.environ.get("MEM0_LLM_MODEL", "Llama-3.3-70B-Instruct")
    mem0_embed   = os.environ.get("MEM0_EMBEDDER_MODEL", "Qwen3-Embedding-8B")

    if not api_key or api_key == "your_regolo_api_key_here":
        print("✗ REGOLO_API_KEY not set. Fill in .env first.")
        sys.exit(1)

    output = MIROFISH_ENV_TEMPLATE.format(
        api_key=api_key,
        base_url=base_url,
        model=model,
        mem0_llm=mem0_llm,
        mem0_embedder=mem0_embed,
    )

    out_path = Path(__file__).parent / "mirofish.env"
    out_path.write_text(output)

    print(f"✓ MiroFish .env written to: {out_path}")
    print(f"  LLM_BASE_URL        = {base_url}")
    print(f"  LLM_MODEL_NAME      = {model}")
    print(f"  MEM0_LLM_MODEL      = {mem0_llm}")
    print(f"  MEM0_EMBEDDER_MODEL = {mem0_embed}")
    print()
    print("Next step:")
    print(f"  cp {out_path} /path/to/MiroFish/.env")


if __name__ == "__main__":
    main()
